class ResolveError(ValueError):
    pass

class RepoError(Exception):
    pass